name: Android Build


on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      #Checking out to the develop branch
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        #Generates the hashes for the comparison between the origin branch and the upstream development branch
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'develop'
      #Installs node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

        #installs yarn
      - name: Install yarn
        run: npm install yarn -g

      - name: Cache Yarn Packages
        id: cache-yarn-packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: yarn-packages-${{ hashFiles('**/yarn.lock') }}

        #installs the yarn lockfile
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build Android Studio Project
        run: yarn nx build:android
      
      - name: Navigatate To Project
        run: cd front-end/android

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/Gym-King.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run:  chmod +x gradlew
      - name: build prod
        run: sh ./gradleBuild.sh
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
